name: ci
on:
  push:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.9.0
        with:
          github_token: ${{ github.token }}
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-web-integration-ci-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-web-integration-ci-
      - name: make
        run: make
