name: ci
on:
  push:
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup pnpm 
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1.13.1
        with:
          github_token: ${{ github.token }}
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.tmp
            .tmp
          key: ${{ runner.os }}-connect-web-integration-ci-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-connect-web-integration-ci-
      - name: Run Make
        run: make test
