name: ci
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: read
    outputs:
      projects: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            buf-ng: angular/**
            buf-astro: astro/**
            buf-express: express/**
            buf-fastify: fastify/**
            buf-nextjs: nextjs/**
            buf-plain: plain/**
            buf-cra: react/cra/**
            buf-esbuild: react/esbuild/**
            buf-parcel: react/parcel/**
            buf-rollup: react/rollup/**
            vite: react/vite/**
            buf-webpack: react/webpack/**
            buf-webpack-cjs: react/webpack-cjs/**
            buf-yarn-pnp: react/yarn-pnp/**
            buf-yarn-unplugged: react/yarn-unplugged/**
            buf-react-native: react-native/**
            buf-remix: remix/**
            buf-svelte: svelte/**
            buf-vanilla-node: vanilla-node/**
            buf-vue: vue/**
  ci:
    needs: changes
    if: ${{ needs.changes.outputs.projects != '' && toJson(fromJson(needs.changes.outputs.projects)) != '[]' }}
    strategy:
      matrix:
        project: ${{ fromJSON(needs.changes.outputs.projects) }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Slightly fragile since it runs on the default node version
      # but until setup-node supports corepack (https://github.com/actions/setup-node/issues/531)
      # this is our best option
      - name: Enable core pack
        run: |
          corepack enable
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run CI
        run: node manage.mjs ci ${{ matrix.project }}
      - name: Check Diff
        id: checkdiff
        run: |
          [[ -z $(git status --porcelain | tee /dev/stderr) ]] || exit 1

