name: ci
on:
  pull_request:
  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: read
    outputs:
      projects: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            buf-ng: angular/**
            buf-astro: astro/**
            buf-express: express/**
            buf-fastify: fastify/**
            buf-nextjs: nextjs/**
            buf-plain: plain/**
            buf-cra: react/cra/**
            buf-esbuild: react/esbuild/**
            buf-parcel: react/parcel/**
            buf-rollup: react/rollup/**
            vite: react/vite/**
            buf-webpack: react/webpack/**
            buf-webpack-cjs: react/webpack-cjs/**
            buf-yarn-pnp: react/yarn-pnp/**
            buf-yarn-unplugged: react/yarn-unplugged/**
            buf-react-native: react-native/**
            buf-remix: remix/**
            buf-svelte: svelte/**
            buf-vanilla-node: vanilla-node/**
            buf-vue: vue/**
  ci:
    needs: changes
    strategy:
      matrix:
        project: ${{ fromJSON(needs.changes.outputs.projects) }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1.23.1
        with:
          github_token: ${{ github.token }}
      - name: Run Make
        run: node manage.mjs test {{ matrix.project }}
